services:
  # Go application
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - APPLICATION_NAME=chess
      - DB_DSN=postgresql://namanvashistha@postgres:5432/chess
      - LOG_LEVEL=DEBUG
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - redis
      - postgres
      - kafka
    networks:
      - backend
    volumes:
      - .:/app

  # Redis
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=chess
      - POSTGRES_USER=namanvashistha
      - POSTGRES_PASSWORD=your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  # Zookeeper (for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - backend

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
