services:
  # Go application
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      - PORT=${PORT:-9000}
      - APPLICATION_NAME=${APPLICATION_NAME:-chess}
      - DB_DSN=${DB_DSN:-host=postgres user=namanvashistha dbname=chess password=your_password port=5432 sslmode=disable}
      - REDIS_ADDR=${REDIS_ADDR:-redis:6379}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
    depends_on:
      - redis
      - postgres
    networks:
      - backend

  # Redis
  redis:
    image: redis:7.0
    networks:
      - backend
    volumes:
      - redis_data:/data

  # PostgreSQL
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-chess}
      - POSTGRES_USER=${POSTGRES_USER:-namanvashistha}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-your_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend



networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
