// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"chess-engine/app/controller"
	"chess-engine/app/repository"
	"chess-engine/app/service"
	"github.com/google/wire"
)

// Injectors from injector.go:

func Init() *Initialization {
	gormDB := ConnectToDB()
	userRepositoryImpl := repository.UserRepositoryInit(gormDB)
	userServiceImpl := service.UserServiceInit(userRepositoryImpl)
	userControllerImpl := controller.UserControllerInit(userServiceImpl)
	roleRepositoryImpl := repository.RoleRepositoryInit(gormDB)
	chessRepositoryImpl := repository.ChessRepositoryInit(gormDB)
	chessServiceImpl := service.ChessServiceInit(chessRepositoryImpl)
	chessControllerImpl := controller.ChessControllerInit(chessServiceImpl)

	initialization := NewInitialization(userRepositoryImpl, userServiceImpl, userControllerImpl, roleRepositoryImpl, chessControllerImpl, chessServiceImpl, chessRepositoryImpl)
	return initialization
}

// injector.go:

var db = wire.NewSet(ConnectToDB)

var userServiceSet = wire.NewSet(service.UserServiceInit, wire.Bind(new(service.UserService), new(*service.UserServiceImpl)))

var userRepoSet = wire.NewSet(repository.UserRepositoryInit, wire.Bind(new(repository.UserRepository), new(*repository.UserRepositoryImpl)))

var userCtrlSet = wire.NewSet(controller.UserControllerInit, wire.Bind(new(controller.UserController), new(*controller.UserControllerImpl)))

var roleRepoSet = wire.NewSet(repository.RoleRepositoryInit, wire.Bind(new(repository.RoleRepository), new(*repository.RoleRepositoryImpl)))

var chessRepoSet = wire.NewSet(repository.ChessRepositoryInit, wire.Bind(new(repository.ChessRepository), new(*repository.ChessRepositoryImpl)))

var chessCtrlSet = wire.NewSet(controller.ChessControllerInit, wire.Bind(new(controller.ChessController), new(*controller.ChessControllerImpl)))

var chessSvcSet = wire.NewSet(service.ChessServiceInit, wire.Bind(new(service.ChessService), new(*service.ChessServiceImpl)))
